packages:
  - 'backend/**'
  - 'mobile-app/**'
  - 'vault-web/**'
  - 'web-extension/**'
  # if required, exclude some directories
  - '!backend/dist/**'
  - '!vault-web/dist/**'
  - '!web-extension/dist/**'

onlyBuiltDependencies:
  - '@capaj/type-graphql'
  - '@firebase/util'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - puppeteer
  - react-grab
  - sharp
  - type-graphql
  - vue-demi
  - workerd

overrides:
  ajv: ^8.18.0
  react: ^19.2.4
  react-dom: ^19.2.4
  '@types/react': ^19
  '@types/react-dom': ^19

patchedDependencies:
  '@react-native/gradle-plugin': patches/@react-native__gradle-plugin.patch
  native-base@3.4.28: patches/native-base@3.4.28.patch
  '@graphql-codegen/typescript-react-apollo': patches/@graphql-codegen__typescript-react-apollo.patch

minimumReleaseAgeExclude:
  - '@types/chrome@0.2.0'
  - lint-staged@17.0.8
  - sql-formatter@15.8.2

# minimumReleaseAge: 1440
