nodeLinker: hoisted
packages:
  - 'backend/**'
  - 'mobile-app/**'
  - 'web-extension/**'
  - 'shared/**'
  # if required, exclude some directories
  - '!backend/dist/**'
  - '!web-extension/dist/**'
