mutation addNewDeviceForUser(
  $email: EmailAddress!
  $deviceId: UUID!
  $currentAddDeviceSecret: NonEmptyString!
  $input: AddNewDeviceInput!
) {
  deviceDecryptionChallenge(email: $email, deviceId: $deviceId) {
    ... on DecryptionChallengeApproved {
      id
      addNewDeviceForUser(
        currentAddDeviceSecret: $currentAddDeviceSecret
        input: $input
      ) {
        accessToken
        user {
          EncryptedSecrets {
            id
            encrypted
            kind
            createdAt
            updatedAt
            iconUrl
            url
            label
            version
          }
        }
      }
    }
  }
}

mutation deviceDecryptionChallenge($email: EmailAddress!, $deviceId: UUID!) {
  deviceDecryptionChallenge(email: $email, deviceId: $deviceId) {
    ... on DecryptionChallengeApproved {
      id
      addDeviceSecretEncrypted
      encryptionSalt
      userId
      approvedAt
    }
    ... on DecryptionChallengeForApproval {
      id
      approvedAt
    }
  }
}
