mutation deviceDecryptionChallenge($email: EmailAddress!, $deviceId: UUID!) {
  deviceDecryptionChallenge(email: $email, deviceId: $deviceId) {
    ... on DecryptionChallengeMutation {
      id
      addDeviceSecretEncrypted
      encryptionSalt
      userId
      approvedAt
    }
    ... on DecryptionChallengeForApproval {
      id
      approvedAt
    }
  }
}

mutation addNewDeviceForUser(
  $currentAddDeviceSecret: NonEmptyString!
  $input: AddNewDeviceInput!
) {
  addNewDeviceForUser(
    currentAddDeviceSecret: $currentAddDeviceSecret
    input: $input
  ) {
    accessToken
    user {
      EncryptedSecrets {
        id
        encrypted
        kind
        createdAt
        updatedAt
        iconUrl
        url
        label
        version
      }
    }
  }
}
