mutation updateSettings(
  $autofill: Boolean!
  $lockTime: Int!
  $language: String!
  $twoFA: Boolean!
) {
  me {
    updateSettings(
      autofill: $autofill
      lockTime: $lockTime
      language: $language
      twoFA: $twoFA
    ) {
      userId
    }
  }
}
