name = "authier-api"
account_id = "fbd16d9252980833034caa69e11aa064"
main = "worker.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
observability = { logs = { enabled = true, invocation_logs = true}}

[vars]
NODE_ENV = "production"

[triggers]
crons = ["*/15 * * * *"]

# Configure secrets with:
# wrangler secret put DATABASE_URL
# wrangler secret put ACCESS_TOKEN_SECRET
# wrangler secret put REFRESH_TOKEN_SECRET
# wrangler secret put COOKIE_SECRET
# ...and the rest of your backend env vars.
