name: 'Build, test and pack WebExtension'
description: 'Builds, tests, and packs extension dir into zip file'

inputs:
  doNotPackZip:
    description: 'Set `true` to omit pack step'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        pnpm i ts-node zx -g
        pnpm i --frozen-lockfile --prefer-offline

    # Add additional build and test steps here
    - name: create .env & web-extension build
      shell: bash
      working-directory: ./web-extension
      run: |
        touch .env
        echo $API_URL >> .env
        echo $PAGE_URL >> .env
        pnpm prodBuild

    # - name: Install Playwright Browsers & Run Playwright tests with backend
    #   shell: bash
    #   working-directory: ./web-extension
    #   run: |
    #     npx playwright install --with-deps
    #     xvfb-run --auto-servernum -- pnpm playwright:run

    # - name: Upload test results
    #   if: always()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: test-results
    #     path: web-extension/test-results
    #     retention-days: 30

    - name: Validate manifest.json of the extension
      uses: cardinalby/schema-validator-action@v1
      with:
        file: ${{ env.EXTENSION_DIR }}manifest.json
        schema: 'https://json.schemastore.org/webextension.json'

    - name: Pack directory to zip
      if: inputs.doNotPackZip != 'true'
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: ${{ env.EXTENSION_DIR }}
        zipFilePath: ${{ env.ZIP_FILE_PATH }}
