mutation RejectChallenge($id: Int!) {
  me {
    decryptionChallenge(id: $id) {
      reject {
        id
      }
    }
  }
}

mutation ApproveChallenge($id: Int!) {
  me {
    decryptionChallenge(id: $id) {
      approve {
        id
      }
    }
  }
}

query DevicesRequests {
  me {
    id
    masterDeviceId
    decryptionChallengesWaiting {
      id
      createdAt
      deviceName
      deviceId
      ipAddress
      ipGeoLocation
    }
  }
}

mutation logoutDevice($id: String!) {
  me {
    device(id: $id) {
      logout {
        id
      }
    }
  }
}

mutation removeDevice($id: String!) {
  me {
    device(id: $id) {
      removeDevice
    }
  }
}

mutation ChangeMasterDevice($newMasterDeviceId: String!) {
  me {
    setMasterDevice(newMasterDeviceId: $newMasterDeviceId) {
      id
    }
  }
}

mutation changeDeviceSettings(
  $id: String!
  $syncTOTP: Boolean!
  $vaultLockTimeoutSeconds: Int!
) {
  me {
    device(id: $id) {
      updateDeviceSettings(
        syncTOTP: $syncTOTP
        vaultLockTimeoutSeconds: $vaultLockTimeoutSeconds
      ) {
        id
      }
    }
  }
}
