mutation updateDefaultDeviceSettings($config: DefaultSettingsInput!) {
  me {
    defaultDeviceSettings {
      id
      update(config: $config) {
        id
        autofillTOTPEnabled
        autofillCredentialsEnabled
        uiLanguage
        deviceTheme
        deviceSyncTOTP
        vaultLockTimeoutSeconds
      }
    }
  }
}

query defaultSettings {
  me {
    id
    defaultDeviceSettings {
      autofillTOTPEnabled
      autofillCredentialsEnabled
      uiLanguage
      deviceTheme
      deviceSyncTOTP
      vaultLockTimeoutSeconds
    }
  }
}
