query encryptedSecrets {
  me {
    id
    encryptedSecrets {
      id
      kind
      encrypted
    }
  }
}

mutation deleteEncryptedSecret($id: ID!) {
  me {
    encryptedSecret(id: $id) {
      id
      delete {
        id
      }
    }
  }
}

mutation removeEncryptedSecrets($secrets: [EncryptedSecretPatchInput!]!) {
  me {
    removeEncryptedSecrets(secrets: $secrets) {
      id
    }
  }
}

mutation updateEncryptedSecret($id: ID!, $patch: EncryptedSecretInput!) {
  me {
    encryptedSecret(id: $id) {
      id
      update(patch: $patch) {
        id
      }
    }
  }
}
