mutation logout {
  currentDevice {
    logout {
      logoutAt
    }
  }
}

mutation markAsSynced {
  currentDevice {
    markAsSynced
  }
}

query SyncEncryptedSecrets {
  currentDevice {
    id
    encryptedSecretsToSync {
      id
      ...secretExtension
    }
  }
}

fragment secretExtension on EncryptedSecretQuery {
  id
  encrypted
  kind
  createdAt
  updatedAt
  deletedAt
  version
}

mutation addEncryptedSecrets($secrets: [EncryptedSecretInput!]!) {
  me {
    addEncryptedSecrets(secrets: $secrets) {
      id
      kind
      encrypted
      version
      createdAt
      updatedAt
    }
  }
}
