mutation addNewDeviceForUser(
  $email: EmailAddress!
  $deviceInput: DeviceInput!
  $currentAddDeviceSecret: NonEmptyString!
  $input: AddNewDeviceInput!
) {
  deviceDecryptionChallenge(email: $email, deviceInput: $deviceInput) {
    ... on DecryptionChallengeApproved {
      id
      addNewDeviceForUser(
        currentAddDeviceSecret: $currentAddDeviceSecret
        input: $input
      ) {
        accessToken
        user {
          id
          EncryptedSecrets {
            id
            encrypted
            kind
            createdAt
            updatedAt
            version
          }
          defaultDeviceTheme
          uiLanguage
          defaultDeviceSyncTOTP
          autofillCredentialsEnabled
          autofillTOTPEnabled
          notificationOnVaultUnlock
          notificationOnWrongPasswordAttempts
        }
      }
    }
  }
}

mutation deviceDecryptionChallenge(
  $email: EmailAddress!
  $deviceInput: DeviceInput!
) {
  deviceDecryptionChallenge(email: $email, deviceInput: $deviceInput) {
    ... on DecryptionChallengeApproved {
      id
      addDeviceSecretEncrypted
      encryptionSalt
      userId
      approvedAt
      deviceId
      deviceName
    }
    ... on DecryptionChallengeForApproval {
      id
    }
  }
}
