mutation addNewDeviceForUser(
  $email: EmailAddress!
  $deviceInput: DeviceInput!
  $currentAddDeviceSecret: NonEmptyString!
  $input: AddNewDeviceInput!
  $deviceId: String!
) {
  deviceDecryptionChallenge(email: $email, deviceInput: $deviceInput) {
    ... on DecryptionChallengeApproved {
      id
      addNewDeviceForUser(
        currentAddDeviceSecret: $currentAddDeviceSecret
        input: $input
      ) {
        accessToken
        user {
          id
          EncryptedSecrets {
            id
            encrypted
            kind
            createdAt
            updatedAt
            version
          }
          notificationOnVaultUnlock
          notificationOnWrongPasswordAttempts
          device(id: $deviceId) {
            id
            syncTOTP
            vaultLockTimeoutSeconds
            autofillCredentialsEnabled
            autofillTOTPEnabled
            uiLanguage
          }
          defaultDeviceSettings {
            id
            autofillTOTPEnabled
            autofillCredentialsEnabled
            uiLanguage
            deviceTheme
            deviceSyncTOTP
            vaultLockTimeoutSeconds
          }
        }
      }
    }
  }
}

mutation deviceDecryptionChallenge(
  $email: EmailAddress!
  $deviceInput: DeviceInput!
) {
  deviceDecryptionChallenge(email: $email, deviceInput: $deviceInput) {
    ... on DecryptionChallengeApproved {
      id
      addDeviceSecretEncrypted
      encryptionSalt
      userId
      approvedAt
      deviceId
      deviceName
    }
    ... on DecryptionChallengeForApproval {
      id
    }
  }
}
