query SyncSettings {
  me {
    id
    loginCredentialsLimit
    TOTPlimit
    notificationOnVaultUnlock
    notificationOnWrongPasswordAttempts
    uiLanguage
    autofillForbiddenUrlPatterns
  }
  currentDevice {
    id
    syncTOTP
    vaultLockTimeoutSeconds
    autofillTOTPEnabled
  }
}

mutation updateSettings($config: SettingsInput!) {
  me {
    updateSettings(config: $config) {
      id
    }
  }
}
