query SyncSettings {
  me {
    loginCredentialsLimit
    TOTPlimit
    id
    autofillCredentialsEnabled
    autofillTOTPEnabled
    uiLanguage
  }
  currentDevice {
    id
    sync2FA
    vaultLockTimeoutSeconds
  }
}

mutation updateSettings($config: SettingsInput!) {
  me {
    updateSettings(config: $config) {
      id
    }
  }
}
