query SyncSettings {
  me {
    loginCredentialsLimit
    TOTPlimit
    id
    notificationOnVaultUnlock
    notificationOnWrongPasswordAttempts
  }
  currentDevice {
    id
    syncTOTP
    vaultLockTimeoutSeconds
    autofillCredentialsEnabled
    autofillTOTPEnabled
    uiLanguage
  }
}

mutation updateSettings($config: SettingsInput!) {
  me {
    updateSettings(config: $config) {
      id
    }
  }
}
