query devicesListWithData {
  me {
    id
    masterDeviceId
    devices {
      id
      name
      firstIpAddress
      lastIpAddress
      logoutAt
      lastGeoLocation
      createdAt
      lastSyncAt
      platform
      createdAt
      syncTOTP
      vaultLockTimeoutSeconds
    }
  }
}
