export enum BackgroundMessageType {
  getAuths = 'getAuths',
  getFirebaseToken = 'getFirebaseToken',
  wasClosed = 'wasClosed',
  getCredentials = 'getCredentials',
  startCount = 'startCount',
  auths = 'auths',
  clear = 'clear',
  passwords = 'passwords',
  securitySettings = 'securitySettings',
  giveSecuritySettings = 'giveSecuritySettings',
  giveUISettings = 'giveUISettings',
  UISettings = 'UISettings',
  saveLoginCredentials = 'saveLoginCredentials',
  getLoginCredentialsModalState = 'getLoginCredentialsModalState',
  hideLoginCredentialsModal = 'hideLoginCredentialsModal',
  saveLoginCredentialsModalShown = 'saveLoginCredentialsModalShown',
  masterPassword = 'masterPassword',
  setMasterPassword = 'setMasterPassword'
}
