mutation addEncryptedSecret($payload: EncryptedSecretInput!) {
  me {
    addEncryptedSecret(payload: $payload) {
      id
      kind
      encrypted
      url
      iconUrl
      label
      version
    }
  }
}
