export enum BackgroundMessageType {
  getFallbackUsernames = 'getFallbackUsernames',
  getBackgroundState = 'getBackgroundState',
  setBackgroundState = 'setBackgroundState',
  getFirebaseToken = 'getFirebaseToken',
  wasClosed = 'wasClosed',
  setUserIdAndMasterPassword = 'setUserIdAndMasterPassword',
  startCount = 'startCount',
  loggedIn = 'loggedIn',
  clear = 'clear',
  passwords = 'passwords',
  securitySettings = 'securitySettings',
  giveSecuritySettings = 'giveSecuritySettings',
  giveUISettings = 'giveUISettings',
  UISettings = 'UISettings',
  addLoginCredentials = 'addLoginCredentials',
  addTOTPSecret = 'addTOTPSecret',
  getLoginCredentialsModalState = 'getLoginCredentialsModalState',
  hideLoginCredentialsModal = 'hideLoginCredentialsModal',
  saveLoginCredentialsModalShown = 'saveLoginCredentialsModalShown'
}
