mutation addEncryptedSecrets($secrets: [EncryptedSecretInput!]!) {
  me {
    addEncryptedSecrets(secrets: $secrets) {
      id
      kind
      encrypted
      version
      createdAt
      updatedAt
    }
  }
}
