mutation addEncryptedSecrets($secrets: [EncryptedSecretInput!]!) {
  me {
    addEncryptedSecrets(secrets: $secrets) {
      id
      kind
      encrypted
      url
      iconUrl
      label
      version
      createdAt
      updatedAt
    }
  }
}
