mutation addWebInputs($webInputs: [WebInputElement!]!) {
  addWebInputs(webInputs: $webInputs) {
    id
  }
}

query webInputsForHost($host: String!) {
  webInputs(host: $host) {
    id
    host
    url
    domPath
    kind
    createdAt
  }
}
