mutation addWebInputs($webInputs: [WebInputElement!]!) {
  addWebInputs(webInputs: $webInputs) {
    id
    createdAt
  }
}

query webInputsForHosts($hosts: [String!]) {
  webInputs(hosts: $hosts) {
    id
    host
    url
    domPath
    domOrdinal
    kind
    createdAt
  }
}
