mutation addWebInputs($webInputs: [WebInputElement!]!) {
  addWebInputs(webInputs: $webInputs) {
    id
    createdAt
    formClassification
  }
}

mutation classifyPasswordForm($input: JSON!) {
  classifyPasswordForm(input: $input) {
    id
    host
    url
    domPath
    domOrdinal
    kind
    createdAt
    formClassification
  }
}

query webInputsForHosts($hosts: [String!]) {
  webInputs(hosts: $hosts) {
    id
    host
    url
    domPath
    domOrdinal
    kind
    createdAt
    formClassification
  }
}
