query settings {
  me {
    settings {
      lockTime
      twoFA
      noHandsLogin
      homeUI
    }
  }
}

query sendAuthMessage(
  $device: String!
  $time: String!
  $location: String!
  $pageName: String!
) {
  me {
    sendAuthMessage(
      device: $device
      time: $time
      location: $location
      pageName: $pageName
    )
  }
}

mutation saveFirebaseToken($firebaseToken: String!) {
  me {
    updateFireToken(firebaseToken: $firebaseToken) {
      id
    }
  }
}
