query isLoggedIn {
  authenticated
}

query settings {
  me {
    settings {
      lockTime
      twoFA
      noHandsLogin
      homeUI
    }
  }
}

mutation saveAuths($payload: String!) {
  me {
    saveAuths(payload: $payload) {
      id
    }
  }
}

mutation savePasswords($payload: String!) {
  me {
    savePasswords(payload: $payload) {
      id
    }
  }
}

query sendAuthMessage(
  $device: String!
  $time: String!
  $location: String!
  $userId: String!
  $pageName: String!
) {
  sendAuthMessage(
    device: $device
    time: $time
    location: $location
    userId: $userId
    pageName: $pageName
  )
}

mutation saveFirebaseToken($firebaseToken: String!) {
  me {
    updateFireToken(firebaseToken: $firebaseToken) {
      id
    }
  }
}
