mutation changeMasterPassword(
  $secrets: [EncryptedSecretPatchInput!]!
  $addDeviceSecret: NonEmptyString!
  $addDeviceSecretEncrypted: NonEmptyString!
  $decryptionChallengeId: PositiveInt!
) {
  me {
    changeMasterPassword(
      input: {
        secrets: $secrets
        addDeviceSecret: $addDeviceSecret
        addDeviceSecretEncrypted: $addDeviceSecretEncrypted
        decryptionChallengeId: $decryptionChallengeId
      }
    )
  }
}
