mutation changeMasterPassword(
  $secrets: [EncryptedSecretPatchInput!]!
  $addDeviceSecret: NonEmptyString!
  $addDeviceSecretEncrypted: NonEmptyString!
  $decryptionChallengeId: PositiveInt!
) {
  me {
    changeMasterPassword(
      input: {
        secrets: $secrets
        addDeviceSecret: $addDeviceSecret
        addDeviceSecretEncrypted: $addDeviceSecretEncrypted
        decryptionChallengeId: $decryptionChallengeId
      }
    )
  }
}

query Account {
  me {
    id
    deviceRecoveryCooldownMinutes
    primaryEmailVerification {
      createdAt
      verifiedAt
    }
  }
}

mutation resendEmailVerification {
  me {
    sendEmailVerification
  }
}

mutation deleteAccount {
  me {
    delete {
      id
    }
  }
}
