mutation deviceDecryptionChallenge($email: EmailAddress!) {
  deviceDecryptionChallenge(email: $email) {
    id
    addDeviceSecretEncrypted
    user {
      id
    }
  }
}

mutation addNewDeviceForUser(
  $currentAddDeviceSecret: NonEmptyString!
  $input: RegisterDeviceInput!
) {
  addNewDeviceForUser(
    currentAddDeviceSecret: $currentAddDeviceSecret
    input: $input
  ) {
    accessToken
    user {
      EncryptedSecrets {
        id
        kind
        encrypted
        url
        iconUrl
        label
        version
      }
    }
  }
}
