mutation deviceDecryptionChallenge($email: EmailAddress!, $deviceId: UUID!) {
  deviceDecryptionChallenge(email: $email, deviceId: $deviceId) {
    id
    addDeviceSecretEncrypted

    user {
      id
    }
  }
}

mutation addNewDeviceForUser(
  $currentAddDeviceSecret: NonEmptyString!
  $input: RegisterDeviceInput!
) {
  addNewDeviceForUser(
    currentAddDeviceSecret: $currentAddDeviceSecret
    input: $input
  ) {
    accessToken
    user {
      EncryptedSecrets {
        id
        encrypted
        kind
        createdAt
        updatedAt
        iconUrl
        url
        label
        version
      }
    }
  }
}
