mutation registerNewUser($input: RegisterDeviceInput!, $userId: UUID!) {
  registerNewUser(input: $input, userId: $userId) {
    accessToken
    user {
      id
      Devices {
        id
        name
      }
    }
  }
}
