mutation registerNewUser($input: RegisterNewDeviceInput!, $userId: UUID!) {
  registerNewUser(input: $input, userId: $userId) {
    accessToken

    user {
      id
      EncryptedSecrets {
        encrypted
        kind
        id
      }
    }
  }
}

mutation deviceDecryptionChallenge($email: EmailAddress!) {
  deviceDecryptionChallenge(email: $email) {
    id
    addDeviceSecretEncrypted
  }
}
