mutation registerNewUser($input: RegisterNewDeviceInput!, $userId: UUID!) {
  registerNewUser(input: $input, userId: $userId) {
    accessToken
    user {
      id
      Devices {
        id
        name
      }
    }
  }
}

mutation deviceDecryptionChallenge($email: EmailAddress!) {
  deviceDecryptionChallenge(email: $email) {
    id
    addDeviceSecretEncrypted
  }
}
