name: Authier deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: monorepo deploy
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm i ts-node zx -g
          pnpm i --frozen-lockfile --prefer-offline

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
            webExtension:
              - 'web-extension/**'
            mobileApp:
              - 'mobile-app/**'

      - name: backend build and deploy
        working-directory: ./backend
        if: steps.changes.outputs.backend == 'true'
        run: |
          pnpm gen
          pnpm migrate
          pnpm cdkDeploy

      - name: Create backend Sentry release
        if: steps.changes.outputs.backend == 'true'
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: authier-ml
          SENTRY_PROJECT: authier-7k
        with:
          environment: production
