name: Build and deploy chrome extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build chrome extension
    runs-on: ubuntu-latest    
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
    
    - name: Install dependencies
      run: |
          pnpm i --frozen-lockfile --prefer-offline
          pnpm i ts-node -g
    
    - name: Web-extension build
      working-directory: ./web-extension
      run: |
          pnpm prodbuild

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: web-extension/dist

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: web-extension/dist
    
    - name: Zip contents
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r extension.zip dist

    - name: Publish to Chrome store
      uses: Klemensas/chrome-extension-upload-action@v1.3
      with:
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        file-name: './extension.zip'
        app-id: ${{ secrets.CHROME_APP_ID }}
        publish: true