name: Authier monorepo CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: runs typescript, tests, and deploys
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DEBUG: au:*
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
      MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
      MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
      STRIPE_ENDPOINT: ${{ secrets.STRIPE_ENDPOINT }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --prefer-offline

      - name: Cache turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: turbo-${{ runner.os }}-

      - name: Typecheck all packages
        run: pnpm tsc

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/**'
              - 'pnpm-lock.yaml'
            webExtension:
              - 'web-extension/**'
              - '.github/**'
              - 'pnpm-lock.yaml'
            mobileApp:
              - 'mobile-app/**'
              - '.github/**'
              - 'pnpm-lock.yaml'

      - name: backend tests
        working-directory: ./backend
        if: steps.changes.outputs.backend == 'true'
        env:
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test
        run: |
          cp .env.sample .env
          pnpm test

      ## TODO fix sentry release action
      # - name: Create a Sentry.io release
      #   uses: tclindner/sentry-releases-action@v1.2.0
      #   if: steps.changes.outputs.backend == 'true'
      #   env:
      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #     SENTRY_ORG: authier-ml
      #     SENTRY_PROJECT: authier-backend
      #   with:
      #     tagName: ${{ github.sha }}
      #     environment: production

      - name: web-extension tests
        working-directory: ./web-extension
        if: steps.changes.outputs.webExtension == 'true' || steps.changes.outputs.backend == 'true'
        run: pnpm test

      # - name: Install Playwright Browsers & Run Playwright tests with backend
      #   if: steps.changes.outputs.backend == 'true'
      #   working-directory: ./web-extension
      #   run: |
      #     npx playwright install --with-deps
      #     xvfb-run --auto-servernum -- pnpm playwright:run
      #
      # - name: Upload test results
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: web-extension/test-results
      #     retention-days: 30

      - name: mobile-app tests
        working-directory: ./mobile-app
        if: steps.changes.outputs.mobileApp == 'true'
        run: pnpm test
