name: Deloy to caprover
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: AlexxNB/caprover-action@45fdf55f3213582285394908e8a3a0d2df41e21d
      with:
        server: https://captain.caprover-root.subz.fun/
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        appname: authier-api
