name: Deploy Authier services
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: runs typescript and jest
    env:
      CAPROVER_SERVER: ${{secrets.CAPROVER_SERVER}}
      CAPROVER_PASSWORD: ${{secrets.CAPROVER_PASSWORD}}
      APPNAME : authier-api

    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
        # run only if some file in 'src' folder was changed
      - name: api install deps, check TS and run jest
        working-directory: ./backend
        if: steps.changes.outputs.backend == 'true'
        run: |
          yarn --frozen-lockfile
          yarn tsc
          yarn test


      # - uses: AlexxNB/caprover-action@v1
      #   with:
      #     server: https://captain.caprover-root.subz.fun/
      #     password: '${{ secrets.CAPROVER_PASSWORD }}'
      #     appname: authier-api
      #     branch: ${GITHUB_REF##*/}

