name: Deploy Authier services
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to caprover
    env:
      CAPROVER_SERVER: ${{secrets.CAPROVER_SERVER}}
      CAPROVER_PASSWORD: ${{secrets.CAPROVER_PASSWORD}}
      APPNAME : authier-api

    steps:
      - name: Install dependencies
        run: yarn
      - run: npm build
      - run: caprover deploy -h $CAPROVER_SERVER -p $CAPROVER_PASSWORD -a $APPNAME 

