name: publish-on-firefox-add-ons
on:
  workflow_dispatch:
  # Remove on push after dev
  push:
    branches:
      - 'CICD'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cardinalby/export-env-action@v1
        with:
          envFile: './.github/workflows/constants.env'
          expand: true

      - name: Obtain packed zip
        uses: ./.github/workflows/actions/get-zip-asset
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Firefox Addons
        uses: trmcnvn/firefox-addon@v1
        id: addonsDeploy
        with:
          #uuid is only necessary when updating an existing addon,
          # omitting it will create a new addon
          uuid: ${{ secrets.FF_EXTENSION_ID }}
          xpi: ${{ env.ZIP_FILE_PATH }}
          manifest: manifest.json
          api-key: ${{ secrets.FF_JWT_ISSUER }}
          api-secret: ${{ secrets.FF_JWT_SECRET }}

      - name: Abort on upload error
        if: |
          steps.addonsDeploy.outcome == 'failure' &&
          steps.addonsDeploy.outputs.sameVersionAlreadyUploadedError != 'true'
        run: exit 1
