mutation register(
  $password: String!
  $email: String!
  $firebaseToken: String!
) {
  register(password: $password, email: $email, firebaseToken: $firebaseToken) {
    accessToken
    secrets {
      encrypted
    }
  }
}
