query sendAuthMessage(
  $type: String!
  $body: String!
  $title: String!
  $deviceId: String!
) {
  me {
    id
    sendAuthMessage(
      type: $type
      body: $body
      title: $title
      deviceId: $deviceId
    )
  }
}
